#lang sicp
; 这个sicp里，()应该是非法的，得找下None
(define (deriv exp var)
  (cond ((number? exp) 0)
        ((variable? exp) (if (same-variable? exp var) 1 0))
        ((sum? exp) (make-sum (deriv (addend exp) var)
                              (deriv (augend exp) var)))
        ((product? exp)
         (make-sum
          (make-product (multiplier exp)
                        (deriv (multiplicand exp) var))
          (make-product (deriv (multiplier exp) var)
                        (multiplicand exp))))
        ((exponentiation? exp)
         (make-product
          (make-product (exponent exp)
                        (make-exponentiation (base exp) (make-sum (exponent exp) -1)))
          (deriv (base exp) var)))
        (else
          (error "unknown expression type: DERIV" exp))))
; exponentiation
(define (exponentiation? x)
  (and (pair? x) (eq? (cadr x) '**)))
(define (base s) (car s))
(define (exponent s) (caddr s))
(define (make-exponentiation base exponent)
  (cond ((=number? base 0) 0)
        ((=number? exponent 0) 1)
        ((=number? exponent 1) base)
        (else (list base '** exponent))))
; variable and equal? base case
(define (variable? x) (symbol? x))
(define (same-variable? v1 v2)
  (and (variable? v1) (variable? v2) (eq? v1 v2)))
(define (=number? exp num) (and (number? exp) (= exp num)))
; sum
; test
; (sum? '(x * x * x + x)) (addend '(x * x * x + x)) (augend '(x * x * x + x))
; (augend '(x * x + x + x + x)) (addend '(x * x + x + x + x))
; (augend '(x * x + (x + x + x))) (addend '(x * x + (x + x + x)))
; (deriv '((x * x) + x + (x * x)) 'x) (addend '((x * x) + x + (x * x))) (augend '((x * x) + x + (x * x)))
; (deriv '((x + x) + x + x + (x + (x + (x + x)))) 'x)
; (sum? '(x * x * x))
(define (sum? x)
  (if (or (not (pair? x)) (= (length x) 1))
      #f
      (or (eq? (cadr x) '+) (sum? (cddr x)))))
(define (addend s)
  (define (recur s)
    (if (or (null? s) (eq? (car s) '+))
        ()
        (cons (car s) (recur (cdr s)))))
  (let ((ans (recur s)))
       (if (= (length ans) 1)
           (car ans)
           ans)))
(define (augend s)
  (if (eq? (car s) '+)
      (if (= (length (cdr s)) 1)
          (cadr s)
          (cdr s))
      (augend (cdr s))))
(define (make-sum a1 a2)
  (cond ((=number? a1 0) a2)
        ((=number? a2 0) a1)
        ((and (number? a1) (number? a2))
         (+ a1 a2))
        (else (list a1 '+ a2))))
; product
; (product? '(x * x * x)) (product? '(x * x + x)) (product? '(x * x * x + x))
(define (product? x)
  (define (recur? x)
      (cond ((not (pair? x)) #f)
            ((= (length x) 1) #t)
            (else (and (eq? (cadr x) '*) (recur? (cddr x))))))
  (and (pair? x)
       (> (length x) 2)
       (recur? x)))
; (deriv '((x + x) * x * x + (x + (x * (x + x)))) 'x)
; '(x * x * x) '(x * x * x * x) '((x * x) * x * (x * (x + x)))
; test place
(define t1 '(x * x * x))
(define t2 '(x * x * x * x))
(define t3 '((x * x) * x * (x * (x + x))))
(define (multiplier p)
  (car p))
(define (multiplicand p)
  (if (= (length p) 3)
      (caddr p)
      (cddr p)))
(define (make-product m1 m2)
  (cond ((or (=number? m1 0) (=number? m2 0)) 0)
        ((=number? m1 1) m2)
        ((=number? m2 1) m1)
        ((and (number? m1) (number? m2)) (* m1 m2))
        (else (list m1 '* m2))))