(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incorrect-password . l)
    "Incorrect password")
  (define (dispatch pw m)
    (if (eq? pw password)
        (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request: MAKE-ACCOUNT" m)))
        incorrect-password))
  dispatch)

(define (make-account-1 balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incorrect-password . l)
    "Incorrect password")
  (define (dispatch pw m)
    (cond 
      ((not (eq? pw password)) (error "Incorrect password: MAKE-ACCOUNT"))
      ((eq? m 'withdraw) withdraw)
      ((eq? m 'deposit) deposit)
      (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

; test
; (define acc (make-account-1 100 'secret-password))
; (define acc (make-account 100 'secret-password))
; ((acc 'secret-password 'withdraw) 50)
; ((acc 'some-other-password 'withdraw) 60)
; ((acc 'some-other-password 'deposit) 40)
; ((acc 'secret-password 'deposit) 60)