(define (make-account balance password)
  (let ((incorrect-count 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (incorrect-password . l)
      "Incorrect password")
    (define (call-the-cops . l)
      "Incorrect password much times, calling the cops")
    (define (dispatch pw m)
      (if (eq? pw password)
          (begin
            (set! incorrect-count 0)
            (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown request: MAKE-ACCOUNT" m))))
          (begin
            (set! incorrect-count (+ incorrect-count 1))
            (if (> incorrect-count 2)
                call-the-cops
                incorrect-password))))
    dispatch))

(define (make-account-1 balance password)
  (define incorrect-count 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
              balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
    "Incorrect password much times, calling the cops")
  (define (dispatch pw m)
    (cond ((not (eq? pw password))
            (set! incorrect-count (+ incorrect-count 1))
            (if (> incorrect-count 7)
                (lambda (v) (call-the-cops))
                (lambda (v) "Incorrect password")))
          ((eq? m 'withdraw) (set! incorrect-count 0)
                             withdraw)
          ((eq? m 'deposit) (set! incorrect-count 0)
                            deposit)
          ((eq? m 'balance) balance)
          (else (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)
  

; test
; (define acc (make-account-1 100 'secret-password))
; (define acc (make-account 100 'secret-password))
; ((acc 'secret-password 'withdraw) 50)
; ((acc 'some-other-password 'withdraw) 60)
; ((acc 'some-other-password 'deposit) 40)
; ((acc 'secret-password 'deposit) 60)